name: MacOS CI

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 4/5 * *'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        version: ["--HEAD", ""]
      fail-fast: false
    env:
      VERSION: {{ matrix.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name: brew update
      run: brew update
    - name: Get Reverse deps of abseil
      run: brew uses --recursive --include-build --include-test abseil
    - name: Install abseil using C++17
      run: |
        brew install --build-from-source --verbose ./abseil.rb;
        brew test abseil --verbose
    - name: Install dependencies
      run: brew install ${VERSION} --only-dependencies --verbose ./or-tools.rb
    - name: Install OR-Tools
      run: brew install ${VERSION} --build-from-source --verbose ./or-tools.rb
    - run: ls /Users/runner/Library/Logs/Homebrew/or-tools/*
    - name: Info OR-Tools
      run: brew info or-tools --verbose
    - name: List OR-Tools
      run: brew list or-tools --verbose
    - name: Test OR-Tools
      run: brew test or-tools --verbose
    - name: Audit (new-formula) OR-Tools
      run: brew audit --new-formula or-tools
    - name: Audit (strict) OR-Tools
      run: brew audit --strict or-tools
